#!/usr/bin/env python3
"""Regenerate src/journal-lists.js from the ABDC Journal Quality List CSV.

Usage:
    python3 scripts/build-journal-lists.py path/to/abdc-jql.csv

The CSV is the "2022 JQL" sheet of the official ABDC workbook exported with
columns: Journal Title, 2022 rating, Publisher, ISSN, ISSN Online, ...
(the aaronw22/journal-quality GitHub mirror ships exactly that file).

The FT50 list is hard-coded below (Financial Times, 2016 revision, still
current in 2026); its ISSNs are looked up in the ABDC CSV, which contains all
fifty journals.
"""
import csv
import json
import re
import sys
from pathlib import Path

FT50 = [
    "Academy of Management Journal",
    "Academy of Management Review",
    "Accounting, Organizations and Society",
    "Administrative Science Quarterly",
    "American Economic Review",
    "Contemporary Accounting Research",
    "Econometrica",
    "Entrepreneurship Theory and Practice",
    "Harvard Business Review",
    "Human Relations",
    "Human Resource Management",
    "Information Systems Research",
    "Journal of Accounting and Economics",
    "Journal of Accounting Research",
    "Journal of Applied Psychology",
    "Journal of Business Ethics",
    "Journal of Business Venturing",
    "Journal of Consumer Psychology",
    "Journal of Consumer Research",
    "Journal of Finance",
    "Journal of Financial and Quantitative Analysis",
    "Journal of Financial Economics",
    "Journal of International Business Studies",
    "Journal of Management",
    "Journal of Management Information Systems",
    "Journal of Management Studies",
    "Journal of Marketing",
    "Journal of Marketing Research",
    "Journal of Operations Management",
    "Journal of Political Economy",
    "Journal of the Academy of Marketing Science",
    "Management Science",
    "Manufacturing and Service Operations Management",
    "Marketing Science",
    "MIS Quarterly",
    "Operations Research",
    "Organization Science",
    "Organization Studies",
    "Organizational Behavior and Human Decision Processes",
    "Production and Operations Management",
    "Quarterly Journal of Economics",
    "Research Policy",
    "Review of Accounting Studies",
    "Review of Economic Studies",
    "Review of Finance",
    "Review of Financial Studies",
    "MIT Sloan Management Review",
    "Strategic Entrepreneurship Journal",
    "Strategic Management Journal",
    "The Accounting Review",
]

# Extra names the same journal is commonly filed under in Zotero.
FT50_ALIASES = {
    "MIT Sloan Management Review": ["Sloan Management Review"],
    "Manufacturing and Service Operations Management": ["M&SOM"],
    "MIS Quarterly": ["Management Information Systems Quarterly"],
}


def norm(name):
    """Same normalisation as ZoteroJournalRank.normName in src/journal-rank.js."""
    s = name.lower().replace("&", " and ")
    s = re.sub(r"\s*\([^)]*\)\s*$", "", s)  # trailing "(US)", "(UK)" qualifiers
    s = re.sub(r"^the\s+", "", s)
    s = re.sub(r"[^a-z0-9]+", " ", s).strip()
    s = re.sub(r"\s+", " ", s)
    return s


def issns(row):
    out = []
    for key in ("ISSN", "ISSN Online"):
        v = (row.get(key) or "").strip().upper()
        if re.fullmatch(r"\d{4}-\d{3}[\dX]", v) and v not in out:
            out.append(v)
    return out


def main(csv_path):
    rows = list(csv.DictReader(open(csv_path, encoding="utf-8-sig")))
    by_norm = {norm(r["Journal Title"]): r for r in rows}

    ft50 = []
    for name in FT50:
        row = by_norm.get(norm(name))
        if row is None:
            sys.exit(f"FT50 journal not found in ABDC CSV: {name}")
        ft50.append({
            "name": name,
            "aliases": FT50_ALIASES.get(name, []),
            "issn": issns(row),
        })

    abdc = []
    for r in rows:
        rating = (r.get("2022 rating") or "").strip()
        if rating not in ("A*", "A"):
            continue
        abdc.append({
            "name": r["Journal Title"].strip(),
            "rating": rating,
            "issn": issns(r),
        })
    abdc.sort(key=lambda j: j["name"].lower())

    def js_array(items):
        return "[\n" + ",\n".join("\t\t" + json.dumps(i, ensure_ascii=False) for i in items) + ",\n\t]"

    out = Path(__file__).resolve().parent.parent / "src" / "journal-lists.js"
    out.write_text(
        "/* eslint-disable */\n"
        "// GENERATED by scripts/build-journal-lists.py - do not edit by hand.\n"
        "//\n"
        "// Journal lists used by the Journal rank column (src/journal-rank.js):\n"
        "//  - FT50: the Financial Times 50 journals (2016 revision), with ISSNs.\n"
        f"//  - ABDC_A: the {len(abdc)} journals rated A* or A in the ABDC Journal Quality List 2022.\n"
        "\n"
        "var ZoteroJournalLists = {\n"
        f"\tFT50: {js_array(ft50)},\n"
        f"\tABDC_A: {js_array(abdc)},\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"Wrote {out}: {len(ft50)} FT50, {len(abdc)} ABDC A*/A journals")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
